### ISSUE TITLE
[linux] 重定向执行顺序问题

### ISSUE THREAD

**Issue by zhanw15** [inspurcloudgroup/icprd1#11]
![](https://raw.githubusercontent.com/inspurcloudgroup/icprd1/master/%E5%B1%95%E6%9C%9B/Pics/linux_11_10.png)
```shell
# 当使用 cat 参数为不存在文件时会输出错误
$ cat /usr/errfile

# 方法1：使用重定位可屏蔽错误
$ cat /usr/errfile 1>/dev/null 2>&1

# 方法2：下面这种重定位依旧会输出错误
$ cat /usr/errfile 2>&1 1>/dev/null
```
<strong> 为何方法2不能实现屏蔽错误？ </strong>
看到网上说法：方法1中，2>&1 将2重定位到1的地址，从而2也重定位到 /dev/null。  
实验楼上说&1是为了放置被理解为名称为1文件。

**Comment by uchenily** [comment]
重定向的顺序与书写顺序有关
可以看看: https://superuser.com/questions/883087/shell-standard-streams-redirection-order-or-21-1-dev-null-vs-1-dev-null-21
